### ISSUE TITLE
Link to slides

### ISSUE THREAD

**Issue by EstherDeLoof** [OpenWebslides/InnoversityChallengeFinalPitch#1]
@RubenVerborgh Can you put a link on the top of the repository to the slide show?

**Comment by RubenVerborgh** [comment]
Should be there already! It's the blue ribbon on the right (link was fixed in 5a6b0a55dbbcfffd318f7cf2a1df2be8759d2089).

**Comment by EstherDeLoof** [comment]
I actually meant on the top of the GitHub repository we are working in, instead of 'No description or website provided.'

**Comment by RubenVerborgh** [comment]
Oh of course, I misread. Done!
