### ISSUE TITLE
Vertical scrolling bar redundant

### ISSUE THREAD

**Issue by Beramos** [OpenWebslides/InnoversityChallengeFinalPitch#2]
http://rubenverborgh.github.io/InnoversityChallengeFinalPitch/#9

The vertical scrolling bar is redundant at this point

**Comment by EstherDeLoof** [comment]
Not really, we'll still be using the timeline but in a more elegant style

**Comment by RubenVerborgh** [comment]
Redundant indeed; that said, doesn't show on Mac.

**Comment by RubenVerborgh** [comment]
Might or might not be fixed; can you test? If not fixed, not sure how to; I clearly say in the CSS that there should be no vertical scroll bar.

**Comment by Beramos** [comment]
Still there but not important :+1:
