### ISSUE TITLE
Bug slide 5

### ISSUE THREAD

**Issue by Beramos** [OpenWebslides/InnoversityChallengeFinalPitch#3]
![bug](https://cloud.githubusercontent.com/assets/11618908/13443552/cd27683e-e001-11e5-96d9-f0afaef3ca32.png)

Linux/Google-chrome

**Comment by RubenVerborgh** [comment]
Esther had the same; will fix.

**Comment by EstherDeLoof** [comment]
I have the exact same problem on my Windows Chrome

**Comment by EstherDeLoof** [comment]
Indeed

**Comment by RubenVerborgh** [comment]
Probably slightly different font rendering. Will just make it wider.
