### ISSUE TITLE
Zoom image framing

### ISSUE THREAD

**Issue by EstherDeLoof** [OpenWebslides/InnoversityChallengeFinalPitch#4]
I've added a more elipse formed image of the network with us in the center. I don't immediately see how to center it.

**Comment by RubenVerborgh** [comment]
Perfect, will center it. (The code for doing that is located in the CSS file.)
Also, the text smoothing looks much better now, because the text is larger.

**Comment by EstherDeLoof** [comment]
Super, thanks!

**Comment by RubenVerborgh** [comment]
You outdid yourself, it looks really splendid now!
